[package]
name = "aurex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.10.1"
rand = "0.9.0"
wmidi = "4.0.10"
